services:
  - type: web
    name: moviebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PRIVATE_CHANNEL_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MONGO_URI
        sync: false
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
