services:
  - type: web
    name: telegram-movie-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: PRIVATE_CHANNEL_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
